// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/asistencia': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/asistencia.post').default>>>>
    }
    '/api/logros': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logros.post').default>>>>
    }
    '/api/planteles/:plantel/bootstrap': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/planteles/[plantel]/bootstrap.get').default>>>>
    }
    '/api/planteles/:plantel/grupos/:grado/:grupo/asistencia-hoy': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/planteles/[plantel]/grupos/[grado]/[grupo]/asistencia-hoy.get').default>>>>
    }
    '/api/planteles/:plantel/grupos/:grado/:grupo/logros-estado': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/planteles/[plantel]/grupos/[grado]/[grupo]/logros-estado.get').default>>>>
    }
    '/api/planteles/:plantel/grupos/:grado/:grupo/logros-resumen': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/planteles/[plantel]/grupos/[grado]/[grupo]/logros-resumen.get').default>>>>
    }
    '/api/planteles/:plantel/grupos/:grado/:grupo/resumen-semanal': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/planteles/[plantel]/grupos/[grado]/[grupo]/resumen-semanal.get').default>>>>
    }
    '/api/planteles/:plantel/grupos/:grado/:grupo/retardos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/planteles/[plantel]/grupos/[grado]/[grupo]/retardos.get').default>>>>
    }
    '/api/planteles/:plantel/grupos/:grado/:grupo/roster': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/planteles/[plantel]/grupos/[grado]/[grupo]/roster.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}